

server.port: 8182

spring.application.name: discovery-service-two

#spring.cloud.config.enabled: true

microservice.contextpath: '/service/demo/test'

eureka.client.registerWithEureka: true
eureka.client.fetchRegistery: true
eureka.instance.perferIpAddress: true

eureka:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

